---

site_name: PowervRA
repo_url: https://github.com/jakkulabs/PowervRA
site_author: JakkuLabs
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PowervRA is licensed under the <a href='https://github.com/jakkulabs/PowervRA/raw/master/LICENSE'>MIT license"
pages:
- 'Home' : 'index.md'
- 'Change log' : 'CHANGELOG.md'
- 'Build' : 'build.md'
- 'Functions':
    - Add-vRAPrincipalToTenantRole : functions/Add-vRAPrincipalToTenantRole.md
    - Add-vRAReservationNetwork : functions/Add-vRAReservationNetwork.md
    - Add-vRAReservationStorage : functions/Add-vRAReservationStorage.md
    - Connect-vRAServer : functions/Connect-vRAServer.md
    - Disconnect-vRAServer : functions/Disconnect-vRAServer.md
    - Export-vRAIcon : functions/Export-vRAIcon.md
    - Export-vRAPackage : functions/Export-vRAPackage.md
    - Get-vRAApplianceServiceStatus : functions/Get-vRAApplianceServiceStatus.md
    - Get-vRAAuthorizationRole : functions/Get-vRAAuthorizationRole.md
    - Get-vRABlueprint : functions/Get-vRABlueprint.md
    - Get-vRABusinessGroup : functions/Get-vRABusinessGroup.md
    - Get-vRACatalogItem : functions/Get-vRACatalogItem.md
    - Get-vRACatalogItemRequestTemplate : functions/Get-vRACatalogItemRequestTemplate.md
    - Get-vRACatalogPrincipal : functions/Get-vRACatalogPrincipal.md
    - Get-vRAComponentRegistryService : functions/Get-vRAComponentRegistryService.md
    - Get-vRAComponentRegistryServiceEndpoint : functions/Get-vRAComponentRegistryServiceEndpoint.md
    - Get-vRAComponentRegistryServiceStatus : functions/Get-vRAComponentRegistryServiceStatus.md
    - Get-vRAContent : functions/Get-vRAContent.md
    - Get-vRAContentData : functions/Get-vRAContentData.md
    - Get-vRAContentType : functions/Get-vRAContentType.md
    - Get-vRAEntitledCatalogItem : functions/Get-vRAEntitledCatalogItem.md
    - Get-vRAEntitledService : functions/Get-vRAEntitledService.md
    - Get-vRAEntitlement : functions/Get-vRAEntitlement.md
    - Get-vRAExternalNetworkProfile : functions/Get-vRAExternalNetworkProfile.md
    - Get-vRAGroupPrincipal : functions/Get-vRAGroupPrincipal.md
    - Get-vRAIcon : functions/Get-vRAIcon.md
    - Get-vRANATNetworkProfile : functions/Get-vRANATNetworkProfile.md
    - Get-vRANetworkProfileIPAddressList : functions/Get-vRANetworkProfileIPAddressList.md
    - Get-vRANetworkProfileIPRangeSummary : functions/Get-vRANetworkProfileIPRangeSummary.md
    - Get-vRAPackage : functions/Get-vRAPackage.md
    - Get-vRAPackageContent : functions/Get-vRAPackageContent.md
    - Get-vRAPropertyDefinition : functions/Get-vRAPropertyDefinition.md
    - Get-vRARequest : functions/Get-vRARequest.md
    - Get-vRAReservation : functions/Get-vRAReservation.md
    - Get-vRAReservationComputeResource : functions/Get-vRAReservationComputeResource.md
    - Get-vRAReservationComputeResourceMemory : functions/Get-vRAReservationComputeResourceMemory.md
    - Get-vRAReservationComputeResourceNetwork : functions/Get-vRAReservationComputeResourceNetwork.md
    - Get-vRAReservationComputeResourceResourcePool : functions/Get-vRAReservationComputeResourceResourcePool.md
    - Get-vRAReservationComputeResourceStorage : functions/Get-vRAReservationComputeResourceStorage.md
    - Get-vRAReservationPolicy : functions/Get-vRAReservationPolicy.md
    - Get-vRAReservationTemplate : functions/Get-vRAReservationTemplate.md
    - Get-vRAReservationType : functions/Get-vRAReservationType.md
    - Get-vRAResource : functions/Get-vRAResource.md
    - Get-vRAResourceAction : functions/Get-vRAResourceAction.md
    - Get-vRAResourceActionRequestTemplate : functions/Get-vRAResourceActionRequestTemplate.md
    - Get-vRAResourceMetric : functions/Get-vRAResourceMetric.md
    - Get-vRAResourceOperation : functions/Get-vRAResourceOperation.md
    - Get-vRAResourceType : functions/Get-vRAResourceType.md
    - Get-vRARoutedNetworkProfile : functions/Get-vRARoutedNetworkProfile.md
    - Get-vRAService : functions/Get-vRAService.md
    - Get-vRAServiceBlueprint : functions/Get-vRAServiceBlueprint.md
    - Get-vRASourceMachine : functions/Get-vRASourceMachine.md
    - Get-vRAStorageReservationPolicy : functions/Get-vRAStorageReservationPolicy.md
    - Get-vRATenant : functions/Get-vRATenant.md
    - Get-vRATenantDirectory : functions/Get-vRATenantDirectory.md
    - Get-vRATenantDirectoryStatus : functions/Get-vRATenantDirectoryStatus.md
    - Get-vRATenantRole : functions/Get-vRATenantRole.md
    - Get-vRAUserPrincipal : functions/Get-vRAUserPrincipal.md
    - Get-vRAUserPrincipalGroupMembership : functions/Get-vRAUserPrincipalGroupMembership.md
    - Get-vRAVersion : functions/Get-vRAVersion.md
    - Import-vRAIcon : functions/Import-vRAIcon.md
    - Import-vRAPackage : functions/Import-vRAPackage.md
    - Invoke-vRADataCollection : functions/Invoke-vRADataCollection.md
    - Invoke-vRARestMethod : functions/Invoke-vRARestMethod.md
    - New-vRABusinessGroup : functions/New-vRABusinessGroup.md
    - New-vRAEntitlement : functions/New-vRAEntitlement.md
    - New-vRAExternalNetworkProfile : functions/New-vRAExternalNetworkProfile.md
    - New-vRAGroupPrincipal : functions/New-vRAGroupPrincipal.md
    - New-vRANATNetworkProfile : functions/New-vRANATNetworkProfile.md
    - New-vRANetworkProfileIPRangeDefinition : functions/New-vRANetworkProfileIPRangeDefinition.md
    - New-vRAPackage : functions/New-vRAPackage.md
    - New-vRAPropertyDefinition : functions/New-vRAPropertyDefinition.md
    - New-vRAReservation : functions/New-vRAReservation.md
    - New-vRAReservationNetworkDefinition : functions/New-vRAReservationNetworkDefinition.md
    - New-vRAReservationPolicy : functions/New-vRAReservationPolicy.md
    - New-vRAReservationStorageDefinition : functions/New-vRAReservationStorageDefinition.md
    - New-vRARoutedNetworkProfile : functions/New-vRARoutedNetworkProfile.md
    - New-vRAService : functions/New-vRAService.md
    - New-vRAStorageReservationPolicy : functions/New-vRAStorageReservationPolicy.md
    - New-vRATenant : functions/New-vRATenant.md
    - New-vRATenantDirectory : functions/New-vRATenantDirectory.md
    - New-vRAUserPrincipal : functions/New-vRAUserPrincipal.md
    - Remove-vRABusinessGroup : functions/Remove-vRABusinessGroup.md
    - Remove-vRAExternalNetworkProfile : functions/Remove-vRAExternalNetworkProfile.md
    - Remove-vRAGroupPrincipal : functions/Remove-vRAGroupPrincipal.md
    - Remove-vRAIcon : functions/Remove-vRAIcon.md
    - Remove-vRANATNetworkProfile : functions/Remove-vRANATNetworkProfile.md
    - Remove-vRAPackage : functions/Remove-vRAPackage.md
    - Remove-vRAPrincipalFromTenantRole : functions/Remove-vRAPrincipalFromTenantRole.md
    - Remove-vRAPropertyDefinition : functions/Remove-vRAPropertyDefinition.md
    - Remove-vRAReservation : functions/Remove-vRAReservation.md
    - Remove-vRAReservationNetwork : functions/Remove-vRAReservationNetwork.md
    - Remove-vRAReservationPolicy : functions/Remove-vRAReservationPolicy.md
    - Remove-vRAReservationStorage : functions/Remove-vRAReservationStorage.md
    - Remove-vRARoutedNetworkProfile : functions/Remove-vRARoutedNetworkProfile.md
    - Remove-vRAService : functions/Remove-vRAService.md
    - Remove-vRAStorageReservationPolicy : functions/Remove-vRAStorageReservationPolicy.md
    - Remove-vRATenant : functions/Remove-vRATenant.md
    - Remove-vRATenantDirectory : functions/Remove-vRATenantDirectory.md
    - Remove-vRAUserPrincipal : functions/Remove-vRAUserPrincipal.md
    - Request-vRACatalogItem : functions/Request-vRACatalogItem.md
    - Request-vRAResourceAction : functions/Request-vRAResourceAction.md
    - Set-vRABusinessGroup : functions/Set-vRABusinessGroup.md
    - Set-vRACatalogItem : functions/Set-vRACatalogItem.md
    - Set-vRAEntitlement : functions/Set-vRAEntitlement.md
    - Set-vRAExternalNetworkProfile : functions/Set-vRAExternalNetworkProfile.md
    - Set-vRANATNetworkProfile : functions/Set-vRANATNetworkProfile.md
    - Set-vRAReservation : functions/Set-vRAReservation.md
    - Set-vRAReservationNetwork : functions/Set-vRAReservationNetwork.md
    - Set-vRAReservationPolicy : functions/Set-vRAReservationPolicy.md
    - Set-vRAReservationStorage : functions/Set-vRAReservationStorage.md
    - Set-vRARoutedNetworkProfile : functions/Set-vRARoutedNetworkProfile.md
    - Set-vRAService : functions/Set-vRAService.md
    - Set-vRAStorageReservationPolicy : functions/Set-vRAStorageReservationPolicy.md
    - Set-vRATenant : functions/Set-vRATenant.md
    - Set-vRATenantDirectory : functions/Set-vRATenantDirectory.md
    - Set-vRAUserPrincipal : functions/Set-vRAUserPrincipal.md
    - Test-vRAPackage : functions/Test-vRAPackage.md
